### ISSUE TITLE
Vertical Tabs

### ISSUE THREAD

**Issue by nor0x** [roubachof/Sharpnado.Tabs#1]
**Describe the solution you'd like**

First of all - thank you for yet another great component for Xamarin.Forms. I'm already using some of your other packages and have to say that it's a joy using them 👏

i was wondering if these tabs can also be displayed vertically - the `TabHostView` contains a `Grid` and a `ScrollView` which could both handle vertical layouting i guess. I know that there is more to it obviously but i was curious if Vertical Tabs are interesting for you?

More and more apps, especially on landscape orientation (Desktop, Tablets,...) are using vertical tabs as their main navigation mechanism. i.e. Discord, MS Teams, MS Edge, Mac App Store...

**Describe alternatives you've considered**
Could probably be done with a Main-Detail layout, but this seems to more suited for showing very similar views and just chaning the underlying data for the detatil view

**Additional context**
Here are some examples:
<img width="1433" alt="IMG_12389123" src="https://user-images.githubusercontent.com/3210391/97561936-2f7d2a00-19e1-11eb-8cbf-cd8b6378c844.png">
©redit [https://dribbble.com/shots/13818645-Project-Kanban-Style](https://dribbble.com/shots/13818645-Project-Kanban-Style)
©redit [https://dribbble.com/shots/14158637-Deals](https://dribbble.com/shots/14158637-Deals)
©redit [https://dribbble.com/shots/9834917-Careers-Hiring-Job-Admin-UI-Design/attachments/1867783?mode=media](https://dribbble.com/shots/9834917-Careers-Hiring-Job-Admin-UI-Design/attachments/1867783?mode=media)
©redit [https://dribbble.com/shots/13616742-User-Profile](https://dribbble.com/shots/13616742-User-Profile)

**Comment by roubachof** [comment]
Thank you for the kind words :)
Man, each time I make a release I say to myself: "job done here, I think there is not more functionalities that can be added".
And each time 30 sec after the release someone comes up with a new idea x)

So I must say it's a really interesting idea :)
But I guess I won't be working on tabs any time soon.
My task list is:

* HorizontalListView new release
* TaskLoaderView new release
* ...

So feel free to submit a PR :)

**Comment by nor0x** [comment]
it's a great piece of software so no rush because of my ideas 😉
i will take a look at it and see if i can contribute.
Thanks!

**Comment by bobbyqul** [comment]
Anything new here? I am also interested in vertical tabs.

**Comment by nor0x** [comment]
i'm actively working on a PR, gonna publish it soon :-)

**Comment by nor0x** [comment]
making some more progress on vertical tabs, so my question to @roubachof. I will add the PR to `Sharpnado.Tabs` of course, but i have also forked `Xamarin-Forms-Practices` to build the vertical showcase. Should i PR these changes as well?

![IMG_15s14s468](https://user-images.githubusercontent.com/3210391/99726669-11be5480-2ab7-11eb-8ae2-e73e95babe10.jpg)

**Comment by roubachof** [comment]
@nor0x I will have a look at this soon, so:

could you submit a pr on the Xamarin-Forms-Practices repo as well?

The idea is to detect if you are in landscape mode, and if yes put the tabs vertically instead of horizontally (it doesn't need to work dynamically, would be a plus but... :)

**Comment by roubachof** [comment]
forget about this message, after some thinking, I think it's best if I implement it myself on the Silly! app.
This way I could validate the implementation.

**Comment by roubachof** [comment]
Will be fixed by tabs v2.1 coming out next week.
