### ISSUE TITLE
Swipe Feature for ViewSwitcher

### ISSUE THREAD

**Issue by ashishkumawat** [roubachof/Sharpnado.Tabs#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by roubachof** [comment]
Use a collection view carousel or CardsView instead of the ViewSwitcher and bind selected index on collection current index

**Comment by samir-dahal** [comment]
You can use this:
https://github.com/chaosifier/TabView
This has exactly what you need.

**Comment by roubachof** [comment]
TabView is using the collection view underneath so it's pretty much the same
