### ISSUE TITLE
MAUI - FontIcon for IconImageSource padding

### ISSUE THREAD

**Issue by m1dst** [roubachof/Sharpnado.Tabs#102]
**Platform (please complete the following information):**
 - OS: Android
 - Device: AndroidEmulator
 - Sdk version: API30
 - MAUI: [8.0.3]

**Describe the bug**
I tried replacing a png with a fonticon and the scaling and padding was ignored.

```
<tabs:TabButton
    x:Name="TabButton"
    ButtonBackgroundColor="{StaticResource Primary}"
    ButtonCircleSize="60"
    ButtonPadding="20"
    IconImageSource="camera_96.png"
     />
```

produces 
![image](https://github.com/roubachof/Sharpnado.Tabs/assets/958968/112bdaad-1892-4347-852b-3991164b3033)

```
  <tabs:TabButton
      x:Name="TabButton"
      ButtonBackgroundColor="{StaticResource Primary}"
      ButtonCircleSize="60"
      ButtonPadding="20"
      IconImageSource="{FontImage {StaticResource fa-camera},
        FontFamily=FontAwesomeSolid,
        Color='White',
        Size=96 }"
       />
```

produces
![image](https://github.com/roubachof/Sharpnado.Tabs/assets/958968/f9eea532-b76e-4e7a-a11e-063c1a531652)

If I edit the ButtonPadding to zero and then back to 20 using the live editor then it works as expected.

![image](https://github.com/roubachof/Sharpnado.Tabs/assets/958968/f6cac7e9-bcc3-4ee0-be8d-75c71289ff92)

**Comment by m1dst** [comment]
Perhaps it is related to this? https://github.com/dotnet/maui/issues/18857

**Comment by FreakyAli** [comment]
@m1dst Do you think it has something to do with the size you are setting to your icon in `IconImageSource`?

**Comment by m1dst** [comment]
I've since found this is a Maui bug. It has been fixed in the next release of Maui but isn't available today.
