### ISSUE TITLE
[MAUI] The Switcher does not update the TabHost

### ISSUE THREAD

**Issue by Agredo** [roubachof/Sharpnado.Tabs#106]
**Platform (please complete the following information):**
 - OS: [Both]
 - Device: [Samsung galaxy A6, iPhone 12 mini]
 - Sdk vervion: [iOS 17/Android SDK 21]
 - MAUI: [8.0.21]

**Describe the bug**
The switcher des not update when clicking

**To Reproduce**

The Switcher does not update the TabHost

The Code:
`<ContentPage
    x:Class="UniTracks.Maui.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:controls="clr-namespace:UniTracks.Maui.Views.Controls;assembly=UniTracks.Maui.Views"
    xmlns:pages="clr-namespace:UniTracks.Maui.Views.Pages;assembly=UniTracks.Maui.Views"
    xmlns:pagesViewModels="clr-namespace:UniTracks.ViewModels.Pages;assembly=UniTracks.ViewModels"
    xmlns:tabViews="clr-namespace:UniTracks.Maui.Views.Tabs.StartPage;assembly=UniTracks.Maui.Views"
    xmlns:tabs="http://sharpnado.com"
    xmlns:viewModels="clr-namespace:UniTracks.ViewModels;assembly=UniTracks.ViewModels"
    x:DataType="viewModels:MainPageViewModel">

    <Grid RowDefinitions="*, Auto">
        

        <tabs:ViewSwitcher
            x:Name="Switcher"
            Animate="True"
            SelectedIndex="{Binding SelectedViewModelIndex, Mode=TwoWay}">

            <tabViews:TripsTab
                SelectedTrip="{Binding SelectedTrip, Mode=TwoWay}"
                SelectionChaged="{Binding SelectedTripChangedCommand}"
                Trips="{Binding Trips}" />
            <ContentView>
                <HorizontalStackLayout
                    HorizontalOptions="Center"
                    Spacing="8"
                    VerticalOptions="End">
                    <Button Command="{Binding StartListeningCommand}" Text="Start Trip" />
                    <Button Command="{Binding StopListeningCommand}" Text="Stop Trip" />
                </HorizontalStackLayout>
            </ContentView>

            <ContentView>
                <HorizontalStackLayout
                    HorizontalOptions="Center"
                    Spacing="8"
                    VerticalOptions="End">
                    <Button Command="{Binding StartListeningCommand}" Text="Start Trip" />
                    <Button Command="{Binding StopListeningCommand}" Text="Stop Trip" />
                </HorizontalStackLayout>
            </ContentView>
        </tabs:ViewSwitcher>

        <tabs:TabHostView
            x:Name="MainTabsHost"
            Grid.Row="1"
            SelectedIndex="{Binding Source={x:Reference Switcher}, Path=SelectedIndex, Mode=TwoWay}">
            <tabs:BottomTabItem HeightRequest="48" Label="Home" />
            <tabs:BottomTabItem HeightRequest="48" Label="Tracks" />
        </tabs:TabHostView>
    </Grid>

</ContentPage>
`
`    private int selectedViewModelIndex;
    public int SelectedViewModelIndex { 
        get 
        { 
            return selectedViewModelIndex;  
        } 
        set 
        { 
            selectedViewModelIndex = value;
            SetProperty(ref selectedViewModelIndex, value);
        }
    }`

```

**Screenshots (if applicable)**
If applicable, add screenshots to help explain your problem.

**Comment by FreakyAli** [comment]
Either your property `SelectedViewModelIndex `  is not getting updated when you change it or your ViewModel is not bound to the Page when you are doing this

**Comment by roubachof** [comment]
@FreakyAli is right.
