### ISSUE TITLE
[MAUI] TabHostView.Shades - NeumorphismShades looking shadow?

### ISSUE THREAD

**Issue by nk-alex** [roubachof/Sharpnado.Tabs#107]
I really enjoyed **TabHostView.Shades** back in Xamarin.Forms. I read you are not planning on porting [Sharpnado.Shadows](https://github.com/roubachof/Sharpnado.Shadows) to MAUI. So I was wondering if the new MAUI shadows could somehow achieve the same aspect as NeumorphismShades.

**Comment by roubachof** [comment]
unfortunately it cannot since maui only support one shadow at a time
