### ISSUE TITLE
[MAUI] DelayedView LoadingTemplate or Loading Content?

### ISSUE THREAD

**Issue by LeoJHarris** [roubachof/Sharpnado.Tabs#113]
**Describe the solution you'd like**
When pages loads with `DelayedView` a activity indicator shows but it would be nice to have an option to provide some other visual indicator of page loading like skeleton loading into a `LoadingView`?

Something like the following:

```xaml
<tabs:DelayedView  Animate="True" UseActivityIndicator="False" ... >
                        <tabs:DelayedView.LoadingView>
                        <!--some loadingview or control template option?-->
                        </tabs:DelayedView.LoadingView>
</tabs:DelayedView>
```

**Describe alternatives you've considered**
Currently we use the the following that requires a bit more involvement of switching layout but ideally we could utilize `DelayedView` view switching and its improved performance, currently we still using `LazyView`

```xaml
<Grid toolkit:StateContainer.CurrentState="{Binding CurrentPageState}">
                        <toolkit:StateContainer.StateViews>
                            <Grid
                                toolkit:StateView.StateKey="Loading"
```

**Comment by roubachof** [comment]
indeed ! It should be really easy to implement with `ControlTemplate`, please make a PR!

**Comment by LeoJHarris** [comment]
> indeed ! It should be really easy to implement with `ControlTemplate`, please make a PR!

As time permits, I will see what I can do.

**Comment by roubachof** [comment]
https://github.com/user-attachments/assets/aa7d300c-ff65-4946-8c2b-69b55b0ac1df

**Comment by LeoJHarris** [comment]
Great! 💯
