### ISSUE TITLE
Build samples

### ISSUE THREAD

**Issue by JuandreG** [roubachof/Sharpnado.Tabs#115]
I am not able to build any of the samples of Sharpnado. I see these errors in visual studio:

![image](https://github.com/user-attachments/assets/537b4c3c-0be8-42a2-9c6f-b1170c088a89)

This is the version of visual studio I have installed:

![image](https://github.com/user-attachments/assets/ca0052c1-2e8a-4ef1-bda1-9b55c8ebe197)

**Comment by janusw** [comment]
If I try to build the MauiSample with VSCode on MacOS, I see errors like this:

```
error NETSDK1202: The workload 'net6.0-android' is out of support and will not receive security updates in the future.
Please refer to https://aka.ms/maui-support-policy for more information about the support policy.
```

Obviously the lib and samples should be updated to .NET 8 ...

**Comment by janusw** [comment]
I can now build the `MauiSample` on the latest `main` branch again on Mac OS (after #119 has been merged).

@JuandreG Could you check if this also works on Windows with VS2022 now? (I think it should because the CI build on Windows runs through cleanly, and it includes the `MauiSample`).

**Comment by JuandreG** [comment]
They work now thank you.
