### ISSUE TITLE
UnderlinedTabItem with text and icon

### ISSUE THREAD

**Issue by mgierlasinski** [roubachof/Sharpnado.Tabs#13]
First of all, Sharpnado Tabs rocks :metal::satisfied::metal:

There are so many places I found them useful.

Currently we can set only text in `UnderlinedTabItem`. To show image we can use Icon Font but it's not possible to show them both at the same time.

It would be nice to have additional property, maybe `IconImageSource` (to be consistent with `BottomTabItem`) which will allow to set any `ImageSource` next to `Label`.

As an additional option, we could have something like `ContentLayout` in `Button` to control how icon should be displayed relative to text:
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.button.contentlayout?view=xamarin-forms

Alternatively, it could be made Templated :) So we can set any Content instead of just text. When Content is text, it could be converted to label as we have now.

**Comment by roubachof** [comment]
Hey man, don't thing I will implementing this, but you could definitely make a PR.
It's just about inheriting from UnderlinedTabItem and make your own TabItem really :)

**Comment by mkanyo** [comment]
I'm also a fan of Tabs! 🙌 I've had the same need recently when my UX designer added some SVG based icons to the tabs. I've forked your repo and just added a pull request for this - let me know what you think.

**Comment by roubachof** [comment]
DONE in 2.2 \o/
