### ISSUE TITLE
[MAUI] Tab click either does not work and when it does, its really delayed

### ISSUE THREAD

**Issue by FreakyAli** [roubachof/Sharpnado.Tabs#130]
**Platform (please complete the following information):**
 - OS: [Both]
 - Device: [ iPhone11 / Samsung A23 ]
 - Sdk vervion: [iOS 17+/Android SDK 30+]
 - MAUI: [8.0.92]

**Describe the bug**
Tabs click stops working as soon as you upgrade to v3.1.0, works fine if you downgrade to the previous version.

**To Reproduce**
Reproducible in the sample app as well!!

**Comment by roubachof** [comment]
what do you mean by tab click ? the sound ? also nothing changed on ios, it's the same impl

**Comment by FreakyAli** [comment]
On the click of `TabHostView`, items nothing happens there is either a delay to load the tab or it never loads the tab

**Comment by janusw** [comment]
I had the same problem, but only on iOS. It could be fixed by setting `UseMauiTapGesture` to `True` in the `TabHostView`. Could you check if this works for you as well? And you see it also on Android?

See the discussion at https://github.com/roubachof/Sharpnado.Tabs/issues/120#issuecomment-2422698695

**Comment by janusw** [comment]
> **To Reproduce** Steps to reproduce the behavior: Reproducible in the sample app as well!!

Btw, I do not see it in the MauiSample app (on iOS).

**Comment by roubachof** [comment]
Sorry but I cannot reproduce either your issues on the sample (using UseMauiTapGesture or not)

**Comment by roubachof** [comment]
Will close this issue next week if no sample is provided

**Comment by FreakyAli** [comment]
> I had the same problem, but only on iOS. It could be fixed by setting `UseMauiTapGesture` to `True` in the `TabHostView`. Could you check if this works for you as well? And you see it also on Android?
> 
> See the discussion at [#120 (comment)](https://github.com/roubachof/Sharpnado.Tabs/issues/120#issuecomment-2422698695)

This fixes the issue, thanks guys!
