### ISSUE TITLE
[MAUI][ANDROID] Page's BindingContext Does Not Work Wih The First Tab

### ISSUE THREAD

**Issue by sk1llsh0t** [roubachof/Sharpnado.Tabs#132]
Platform (please complete the following information):

OS: [Android]
Device: Tab Active 3 [Android API Level 31]
Sdk Version: Min: 30 Target: 34
MAUI: [NET 8.0][8.0.91]

Bindings on the first tab aren't functioning. Tab 2, 3, etc the bindings work with the bindingcontext of the page's view model. For the first tab however, buttons, label text bindings, etc aren't linked to the page's view model. I use the mauicommunitytoolkit.mvvm package to handle the bindingcontext link.

This issue was introduced after the fix for this issue (https://github.com/roubachof/Sharpnado.Tabs/issues/127#)

I'm currently on sharpnado.tabs 3.1.1

To Reproduce

 - Create an app with the Tabs control (3+ tabs). Add a view model binding for the page containing the tab control.
 -  On each of the tabs, add a button and a label. bind the button command to a relaycommand and the label title to a string property in the view model. I had the button just update the label text's bound property.
 - Run the app and navigate to the page with the tab control
 - You'll notice on the first tab, tapping the button does not trigger the relaycommand in the view model and the label is not updated either. navigating to the other tabs, the bindings work fine (button command is triggered and the label is updated)

Expected Behavior: Bindings on the first tab should work

**Comment by roubachof** [comment]
Need a repro app for that fix

**Comment by sk1llsh0t** [comment]
Repro:
https://github.com/sk1llsh0t/TabVmBindingRepro

When app loads, if i tap the button on the Tab A view, nothing happens. If i go to tab b or c and tap the button, it updates the page label and the label in the tab. go back to tab a and tap the button again, it still doesn't update either label. The relaycommand the button is bound to isn't fired. 

This is also the case if tab b is the default selected tab when the page loads. tab b button binding doesn't work but tab a and tab c work. 

so it is really whichever tab is first to load when the page loads has the issue. not necessarily the first tab in the tabhostview if that makes sense.

**Comment by roubachof** [comment]
Thank you for the repro! Will look into that tomorrow

**Comment by roubachof** [comment]
fixed by v3.2.0

**Comment by sk1llsh0t** [comment]
When will it be uploaded to nuget.org?

**Comment by roubachof** [comment]
Lol I forgot to upload the nuget
