### ISSUE TITLE
Content does not update when switching tabs

### ISSUE THREAD

**Issue by LeoJHarris** [roubachof/Sharpnado.Tabs#141]
**Platform (please complete the following information):**
 - OS: Android
 - Device: AndroidEmulator & Samsung S21
 - Sdk version: Android SDK 35
 - MAUI: 9.0.0

**Describe the bug**
Tapping a tab item does not update the tab content, also the `UnderlinedTabItem` doesnt not show the underline when the page is first navigated to.

**Comment by roubachof** [comment]
erf good old maui regressions, we're never tired of them

**Comment by LeoJHarris** [comment]
@roubachof Do you have any ideas what might be causing this issue? Ill submit a bug report to MAUI as this is going to cause us to roll back on the latest MAUI update.

**Comment by LeoJHarris** [comment]
@roubachof my best bet is now we will have to wait another month or two for issues not previous broken to get fixed again 🤦

**Comment by LeoJHarris** [comment]
Seems to be resolve on the latest 9.0.14 MAUI version so happy to close the issue.

**Comment by roubachof** [comment]
long live maui

**Comment by sthewissen** [comment]
@roubachof I think this might be back around in some shape or form in 9.0.60 and 9.0.70. I can tap the tab title, but the tab doesn't actually switch around. It seems like the backing SelectedIndex property is never set as I'm not hitting any breakpoints there. I've worked around it like this for now;

```csharp
    private void tabHost_SelectedTabIndexChanged(object sender, SelectedPositionChangedEventArgs e)
    {
        if (BindingContext is MyPageModel pm && e.SelectedPosition is int i)
        {
            pm.SelectedTabIndex = i;
        }
    }
```
