### ISSUE TITLE
Load page on demand.

### ISSUE THREAD

**Issue by samir-dahal** [roubachof/Sharpnado.Tabs#16]
Is it possible to load the pages asynchronously while appearing? I cannot find the way to implement this in Sharpnado Tabs?  All the pages in view switcher loads during the startup.

**Comment by roubachof** [comment]
Use LazyView: 

```
<tabs:ViewSwitcher x:Name="Switcher"
                       Grid.Row="1"
                       Animate="False"
                       SelectedIndex="{Binding SelectedViewModelIndex, Mode=TwoWay}">
        <customViews:LazyView x:TypeArguments="tabsLayout:HomeView" BindingContext="{Binding HomePageViewModel}" />
        <customViews:LazyView x:TypeArguments="tabsLayout:ListView" BindingContext="{Binding ListPageViewModel}" />
        <customViews:LazyView x:TypeArguments="tabsLayout:GridView" BindingContext="{Binding GridPageViewModel}" />
    </tabs:ViewSwitcher>

```

**Comment by samir-dahal** [comment]
Do I have to create a class called LazyView and an interface or it comes with sharpnado.presentation.forms?

**Comment by samir-dahal** [comment]
I'm still confused. If pages are loaded on demand if used LazyView then how do I use the OnAppearing method just like in ContentPage? So that I don't have to put my logic for loading inital data in the ctor of all the child view models?

**Comment by roubachof** [comment]
If you are using code behind instead of view models, your content page which is hosting the view switcher is responsible of initializing your data bound to each sub views.

**Comment by samir-dahal** [comment]
I am using sharpnado tabs and trying to load initial data from view model but content view doesn't have on appearing overridable method. So, I am confused.

**Comment by roubachof** [comment]
Please check the sample project to see how view model initialization is done: https://github.com/roubachof/Xamarin-Forms-Practices/blob/master/SillyCompany.Mobile.Practices/Presentation/ViewModels/TabsLayout/SillyBottomTabsPageViewModel.cs

**Comment by samir-dahal** [comment]
The practice project doesn't work all those warnings and errors xD. But I am still curios how you implemented the loading page on demand, in my case I have a viewmodel and sub viewmodels inside that viewmodel
and when the viewmodel is initialized all the corresponding sub viewmodels initialized from viewmodel constructor. Now my requirement is to load the page and show the indicator if its loading only when the page is selected. Thank you by the way. I'll try to figure it out.

**Comment by roubachof** [comment]
The sample works perfectly just read the installation section

**Comment by samir-dahal** [comment]
Please make sure you have the correct access rights
and the repository exists.
--when trying to update submodule..I cloned repository using https.

**Comment by samir-dahal** [comment]
also, is it possible to use content page instead of content view in view switcher? 🤐

**Comment by angelru** [comment]
I don't understand the LazyView example.

```
HomePageViewModel = new HomePageViewModel (navigationService, sillyDudeService);
ListPageViewModel = new ListPageViewModel (navigationService, sillyDudeService, errorEmulator);
GridPageViewModel = new GridPageViewModel (navigationService, sillyDudeService);
```

this loads all viewmodels before the views are loaded, is this the correct working order?

**Comment by roubachof** [comment]
It does not. It builds the view models but not load them. It's the load method which is loading asynchronously the view models.

**Comment by angelru** [comment]
you're right, but then I don't understand how to load the ViewModel when the LazyView loads:

```
          <tabs:ViewSwitcher x:Name="Switcher" Grid.Row="0" Animate="False" Padding="0,16,0,0"
                               SelectedIndex="{Binding SelectedViewModelIndex, Mode=TwoWay}">
                <tabs:LazyView x:TypeArguments="views:ChatsTabPageView" />
            </tabs:ViewSwitcher>
```

```
      public ChatsTabPageView()
        {
            InitializeComponent();

            BindingContext = new ChatsTabPageViewModel();
        }
```

```
        public ChatsTabPageViewModel()
        {
            Init();
        }
```
this does not work for me, the blank view

**Comment by roubachof** [comment]
In the setter of the SelectedViewModelIndex, if you want to only load it when it is selected. Something like:

If (subViewModel.Loader == TaskLoaderNotifier.NotStarted) 
{
    subViewModel.Load()
}

Or just load them all in the load method of your parent view model like here: https://github.com/roubachof/Xamarin-Forms-Practices/blob/master/SillyCompany.Mobile.Practices/Presentation/ViewModels/TabsLayout/SillyBottomTabsPageViewModel.cs

**Comment by angelru** [comment]
I only want to load the ViewModel when the view is requested for the first time. I think with SelectedViewModelIndex it would work, although I must be checking all the ViewModel in my LazyView if they are loaded or not when selecting.

Load the entire ViewModel into the main ViewModel, wouldn't we be loading "unnecessary" data?

**Comment by roubachof** [comment]
It depends on the scenario... sometimes you don't want to block the UI, but you want to display completed view as soon as you click on it. Then LazyView plus load all sub view models is a good fit. If you did good async code (with ConfigureAwait in your services, your loading code will be ran in another thread so it won't slow down your UI rendering.

Also next time use the new "discussion" feature of GitHub to ask questions 😀

**Comment by angelru** [comment]
I would be delighted if you would make an article explaining the service with ConfigureAwait or some link, although I read something about it a long time ago but I do not remember. Regarding the discussion, sorry for the inconvenience, I will do it next time, thank you very much.
