### ISSUE TITLE
Theme not correctly applied on Scrollable UnderlinedTabItem

### ISSUE THREAD

**Issue by jmcruvellier** [roubachof/Sharpnado.Tabs#20]
**Platform:**
 - OS: Android
 - Device: all (AndroidEmulator/OnePlus8Pro)
 - Sdk vervion: [Android SDK 28]
 - Xamarin.Forms: [4.8.0.1821]

**Describe the bug**
I'm currently trying to use 2 Sharpnado tabs in the same screen (1 bottom bar in a page and 1 horizontal scrollable in a view). My issue is on the rendering of Scrollable UnderlinedTabItem when changing the theme dynamically. Only some tabs are having the correct theme applied. The issue does not occur if no tab is selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/14132271/103522479-b84d9180-4e7a-11eb-9fc6-8e586a83c311.png)

**Comment by roubachof** [comment]
a repro would be nice :)

**Comment by roubachof** [comment]
yeah definitely linked to #8. Will be fixed in Tabs 2.1

**Comment by jmcruvellier** [comment]
I confirm, this issue has been fixed in v2.1!
Thanks a lot Jean-Marie

**Comment by leonedev** [comment]
It is not fixed yet, still have this issue
