### ISSUE TITLE
There is no argument given that corresponds to the required formal parameter 'debugLogEnable' of 'Initializer.Initialize(bool, bool)'

### ISSUE THREAD

**Issue by kalisafravy** [roubachof/Sharpnado.Tabs#22]
I am getting an error when I try to initialize Tabs from App.xml.cs 

"**There is no argument given that corresponds to the required formal parameter 'debugLogEnable' of 'Initializer.Initialize(bool, bool)'**"

![image](https://user-images.githubusercontent.com/28753805/104095588-bfc0d080-52a8-11eb-8b03-6fd75b404b57.png)

I have tried cleaning and a couple of many other options but did mot help. Any help?

**Comment by roubachof** [comment]
Yeah that's a typo you should also specify the enableDebug parameter

**Comment by roubachof** [comment]
It should be `Sharpnado.Tabs.Initializer.Initialize(false, false)` (corrected in readme)
