### ISSUE TITLE
Invalid Generic Instantiation

### ISSUE THREAD

**Issue by cdeck95** [roubachof/Sharpnado.Tabs#23]
- OS: [iOS]
 - Device: [iPhone 11 simulator]
 - Sdk vervion: [iOS 14.3]
 - VS for Mac 8.8.5 (build 18)
 - Xamarin.Forms: [5.0.0.1874]

**Bug**: Invalid Instantiation of the LazyView for the tabs in the TabHostView object.

**Steps to reproduce the behavior:**
1. Go to [https://github.com/cdeck95/BestBet](url)
2. Clone the repo
3. Launch the iOS project

**See exception/error screenshot below:**

<img width="1440" alt="Screen Shot 2021-01-17 at 7 03 22 PM" src="https://user-images.githubusercontent.com/14206982/104860162-0ee5b180-58f8-11eb-8580-2166612de9e4.png">

**See the app.cs file & XAML files here:**

<img width="1440" alt="Screen Shot 2021-01-17 at 7 01 28 PM" src="https://user-images.githubusercontent.com/14206982/104860178-2329ae80-58f8-11eb-8834-702e61db2656.png">
<img width="1440" alt="Screen Shot 2021-01-17 at 7 00 53 PM" src="https://user-images.githubusercontent.com/14206982/104860180-24f37200-58f8-11eb-835e-5f95ef506602.png">
<img width="1440" alt="Screen Shot 2021-01-17 at 7 00 01 PM" src="https://user-images.githubusercontent.com/14206982/104860182-26249f00-58f8-11eb-9a0c-332c31e44139.png">
<img width="1440" alt="Screen Shot 2021-01-17 at 6 59 00 PM" src="https://user-images.githubusercontent.com/14206982/104860185-26bd3580-58f8-11eb-83ac-5e37b5597603.png">

If there is anything else you need to know, please let me know.

**Comment by roubachof** [comment]
Hi!
LazyView takes as parameter types that inherit from View not ContentPage :)

**Comment by cdeck95** [comment]
> Hi!
> 
> LazyView takes as parameter types that inherit from View not ContentPage.
> 
> Otherwise I guess I called it LazyPage :) 

Thank you for your quick reply! Now that you say that, I did try to change it to ContentView, but got an error that all my variables and "initantiatecompoment() methods were invalid. Let me get a screenshot.

**Comment by cdeck95** [comment]
@roubachof see screenshot. Do you know why this might be happening? I have tried everything I can think of, but I know its something simple.

<img width="1440" alt="Screen Shot 2021-01-18 at 11 30 31 AM" src="https://user-images.githubusercontent.com/14206982/104941165-b4dcfe80-5980-11eb-87b2-463856471243.png">

**Comment by cdeck95** [comment]
@roubachof I do not want to create a whole new issue for this, but was wondering if you could help. I cannot seem to get my tabs to appear in the lazyview. The page functioned 100% properly before I switched it to appear in a lazyview for the tabs, so I know it is a mistake on my end for the implementation of the lazyview and viewswitcher. 

I added a label to appear called "main page" in the grid row to make sure it wasn't a grid issue. The lazyview just appears to be empty. 

Simulator Screenshot: 

![Simulator Screen Shot - iPhone 11 - 2021-01-18 at 12 43 22](https://user-images.githubusercontent.com/14206982/104948254-04282c80-598b-11eb-9266-1ef67ec350a9.png)

XAML Code for the LazyView Page:

<img width="1440" alt="Screen Shot 2021-01-18 at 12 44 49 PM" src="https://user-images.githubusercontent.com/14206982/104948293-10ac8500-598b-11eb-952c-11144b73929d.png">
<img width="1440" alt="Screen Shot 2021-01-18 at 12 44 17 PM" src="https://user-images.githubusercontent.com/14206982/104948299-11ddb200-598b-11eb-9484-a97e21effb92.png">
