### ISSUE TITLE
Enable Wiki

### ISSUE THREAD

**Issue by tatapuchi** [roubachof/Sharpnado.Tabs#29]
**Describe the solution you'd like**
Could we have the wiki enabled for this plugin so we can add to it, this would help as right now the readme is quite long and the sample project is sort of seperate to Sharpnado.Tabs specfically.

**Describe alternatives you've considered**
A longer readme or a couple more sample projects, but the existence of the sample project and the long readme would be better of just as a short wiki maintained here on the page

**Comment by roubachof** [comment]
wiki is enabled :)

**Comment by tatapuchi** [comment]
Thanks roubachof, I'll try and add to it

**Comment by tatapuchi** [comment]
When i learn how this plugin works a bit better

**Comment by tatapuchi** [comment]
btw, do you guys do work on vertical-tabs and then push to main when production ready? or do u guys just code to main?

**Comment by roubachof** [comment]
vertical tabs are already available

**Comment by roubachof** [comment]
https://github.com/roubachof/Sharpnado.Tabs#vertical-tabs
