### ISSUE TITLE
SegmentedTabItem and BadgeView No text

### ISSUE THREAD

**Issue by georgeemr** [roubachof/Sharpnado.Tabs#33]
If I use this combination, I'm unable to see the text, otherwise, it works well.

![image](https://user-images.githubusercontent.com/3822009/116794184-5d265700-aa88-11eb-82aa-eaadadab5192.png)

`<tabs:TabHostView x:Name="TabHost"
                    Grid.Row="1"
                    HeightRequest="40"
                    Margin="20,15,20,0"
                    VerticalOptions="Center"
                    BackgroundColor="#F0F0F3"
                    Shades="{shades:SingleShade Offset='0,8',
                                            BlurRadius=10,
                                            Color={StaticResource PrimaryColor}, Opacity=0.2}"
                    CornerRadius="20"
                    IsSegmented="True"
                    SegmentedHasSeparator="True"
                    SegmentedOutlineColor="{StaticResource PrimaryColor}"
                    TabType="Fixed"
                    SelectedIndex="{Binding Source={x:Reference Switcher}, Path=SelectedIndex, Mode=TwoWay}">
                <tabs:TabHostView.Tabs>
                    <tabs:SegmentedTabItem Label="Mis números" BackgroundColor="Red" SelectedLabelColor="AliceBlue" SelectedTabColor="Azure">                        
                        <tabs:BadgeView Margin="20,0"
                                HorizontalOptions="Start"
                                VerticalOptions="Center"
                                BackgroundColor="Red"
                                BorderColor="{StaticResource TitleColor}"
                                TextColor="{StaticResource TitleColor}"
                                Text="14" />
                    </tabs:SegmentedTabItem>
                    <tabs:SegmentedTabItem Style="{StaticResource SegmentedTabStyle}" Label="Agregar" />
                </tabs:TabHostView.Tabs>
            </tabs:TabHostView>`

I'm using the last version.

**Comment by roubachof** [comment]
first format correctly your xaml
