### ISSUE TITLE
SelectedTabIndexChanged called multiple times

### ISSUE THREAD

**Issue by ssotir** [roubachof/Sharpnado.Tabs#35]
**Platform (please complete the following information):**
 - OS: Android
 - Device: AndroidEmulator/
 - Sdk version: Android SDK 21
 - Xamarin.Forms: [4.8.0.1451]

**Describe the bug**
I have added an event handler for SelectedTabIndexChanged. Every time I tap on a tab item, this handler is called 3 times. It should be called only once.

**To Reproduce**
Add a SelectedTabIndexChanged handler. Check how many times is called with a tap on a tab item.

**Comment by mphill** [comment]
Looks like multiple tap events are wired in, I am seeing this too.  If you are looking to a way to hook into the hiding and showing of views, I just opened a pr https://github.com/roubachof/Sharpnado.Tabs/pull/38

**Comment by roubachof** [comment]
pr 38 has been merged
