### ISSUE TITLE
NavigationPage for each Tab - is this possible?

### ISSUE THREAD

**Issue by gerricom** [roubachof/Sharpnado.Tabs#37]
First: I'm very sorry but it feels like an absolute rookie question and I'm kind of ashamed to ask... Please be kind

We developed our very first Xamarin.Forms App a while ago and our main concept is a TabbedPage with five individual tabs. Three of five tabs are sophisticated pages that can have some deeper navigational structure. So every of those tree tabs is a NavigationPage that wraps the actual page. From within each tab the user can navigate deeper but she can always change the main tabs to check something else.

This works very nice but then I fell kind of in love with your tabs and the possibilities to style them and have them beautifully arranged. So I tried to figure out how to implement our current use case but I'm not seeing how to do this properly. Yes, the ViewSwitcher needs *views* - got it. But is there something to implement our functionality within a ViewSwitcher and best case with lazy loading?

Thanks for helping out!

**Comment by roubachof** [comment]
Why you should feel ashamed ? It's a totally legit question.
I'm afraid ViewSwitcher as you said, is only supporting views...
Then nested navigation is not supported...
You could maybe try to implement your own TabbedPage and replace native bottom bar with cutoms sharpnado's TabHostView...

**Comment by gerricom** [comment]
Thanks! 

> You could maybe try to implement your own TabbedPage and replace native bottom bar with cutoms sharpnado's TabHostView...

That's what I thought too in the meanwhile. I think I will start fiddling with a custom TabbedPage. I'll come back if I get some positive results.

**Comment by roubachof** [comment]
Great! don't hesitate I would be super interesting in your result :)

**Comment by tklempay** [comment]
@gerricom, I have the EXACT same situation for my Xamarin application.  I know this one is Closed ... but I was wondering if any more thoughts/research/work had been done on this topic.  Thanks for any feedback/comments!

**Comment by roubachof** [comment]
@tklempay don't be shy do your own and open a PR ;)

**Comment by tklempay** [comment]
It's been 6 months since the topic was brought up.  I'm guessing its harder than it appears.  Maybe that's just me.  And oh yeah, I also need this to work in a mixed Xamarin Forms/Native app :/

Rest assured, if I do get somewhere on this, I'll report back.

**Comment by roubachof** [comment]
You shouldn't assume that, devs tend to be afraid of things they don't know. I'm pretty sure that if you take the time you will nail it way quicker than you thought ;)

**Comment by vhugogarcia** [comment]
@gerricom You can implement it by using Sharpnado.Tabs + PRISM Regions. When using the OnShowCommand, you RequestRegionNavigation on PRISM to load the data async from a viewmodel. 👍🏻

**Comment by askariya** [comment]
@vhugogarcia Hi! I was wondering if you happen to have an open source or sample code of that implementation available?
It seems to me like the OnShowCommand will not get called if we don't populate the ViewSwitcher.
