### ISSUE TITLE
Ability to bind Tabs property of a TabHostView

### ISSUE THREAD

**Issue by 15mgm15** [roubachof/Sharpnado.Tabs#4]
**Is your feature request related to a problem? Please describe.**
I was trying to create tabs on the go using the `Tabs` observable collection. I ended up using a workaround but it will be easy to bind the whole object.

**Describe the solution you'd like**
Bindable Tabs of a TabHostView

**Describe alternatives you've considered**
Initialize the Tabs on Xaml and send the `TabHostView` as a parameter to the ViewModel so I can create the dynamic tabs later on.

**Additional context**
We have a feature in which you can have multiple tabs based on how many tables a restaurant has.

**Comment by roubachof** [comment]
Should be fixed by v2.0
