### ISSUE TITLE
Enable FontAwesome for IconImageSource in TabItems

### ISSUE THREAD

**Issue by johnmcbride** [roubachof/Sharpnado.Tabs#43]
Currently you can only enter a string in IconImageSource that is related to an actual resource that has been added to either the forms project or the individual platform projects. It would be nice if you could use something like FontAwesome for Icons in the TabItems

Proposal (allow for backward capability)
Add an additional property that is something like "FontIconImageSource" and a corresponding IValueConvertor to get the icon from the fontawesome library. It would look like the following
<tabs:BottomTabItem FontIconImageSource="{x:Static fontawesome:FontAwesomeIcons.Users}" FontFamily="{StaticResource FontAwesomeSolid}" />

Here is a great article on using fontawesome fonts in a xamarin.forms library. User would have to the the same for this.
https://medium.com/@tsjdevapps/use-fontawesome-in-a-xamarin-forms-app-2edf25311db4

**Describe alternatives you've considered**
Tried to the following the above article and tried this
<tabs:BottomTabItem IconImageSource="{x:Static fontawesome:FontAwesomeIcons.Users}" FontFamily="{StaticResource FontAwesomeSolid}" />

**Comment by roubachof** [comment]
TabItems already support font icons. Maybe you are using an old version of Tabs?

![image](https://user-images.githubusercontent.com/596903/130313139-0fa05769-ff56-4d0a-945a-b53b7361094b.png)

**Comment by johnmcbride** [comment]
What is the recommended way to use the font icons in the tab item?

**Comment by roubachof** [comment]
You can define icon source like this in your styles:

ˋˋˋxml
<FontImageSource x:Key="IconSuccess"
                     FontFamily="FontAwesome"
                     Glyph="{x:Static styles:IconFont.CheckCircle}"
                     Size="{StaticResource SizeMediumSmallIcon}"
                     Color="{StaticResource ColorAlright}" />

ˋˋˋ

**Comment by johnmcbride** [comment]
Interesting,  and you would set the FontIconImageSource property to "IconSuccess" in the above example? It also sounds like you would need multiple FontImageSource for the icons.

**Comment by roubachof** [comment]
Well one font image source for one icon obviously. It's a good practice. And you just set it with classic StaticResource
