### ISSUE TITLE
[UWP] Underline does not disappear when switching Tabs 

### ISSUE THREAD

**Issue by Agredo** [roubachof/Sharpnado.Tabs#45]
**Platform (please complete the following information):**
 - UWP
 - Windows
 - Sdk vervion: Windows 10
 - Xamarin.Forms: [5.0.x]

**Describe the bug**
The underline does not disappears when changing the tabs 

**To Reproduce**
1. Add TabView with multiple Tab
2. Switch betweens Tabs

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/16531090/135008213-ba2fb2a5-6f59-457f-ba31-91f4b9547b63.png)

**Comment by Tremco-MBlodgett** [comment]
Hi Agredo I was playin around with this and found that if you set the corner radius to 1 on the TabHostView then it will clip the unselected bars. You can also wrap your TabHostView in a Frame with 0 padding and that should also fix it.

**Comment by roubachof** [comment]
This a XF trigger bug and it won't be fixed here
