### ISSUE TITLE
Error XFC0000: Cannot resolve type "tabs:TabHostView"

### ISSUE THREAD

**Issue by roubachof** [roubachof/Sharpnado.Tabs#5]
If you end up with this error, it means you forgot to call the Sharpnado.Tabs.Initializer.Initialize() in your App.xaml.cs.
Have a look here: https://github.com/roubachof/Sharpnado.Tabs#installation

**Comment by brentpbc** [comment]
hi @roubachof, 
I am getting error XFC0000 any time I make a change to my xaml file. But it does not stop the app from compiling or running as expected though. Note I am running VS for Mac

`/TestTabControlPage.xaml: Error:  : XamlC error XFC0000 : Cannot resolve type "TabHostView".`


I have added the initialiser statement to my App.xaml.cs
![image](https://user-images.githubusercontent.com/55366323/97927612-6d9b9480-1db9-11eb-88cc-4ad480ea2531.png)

Errors in error window when ever I change the xaml file,Note if I quit VS and reopen the solution the errors go away until I modify the file :
![image](https://user-images.githubusercontent.com/55366323/97927680-902dad80-1db9-11eb-865c-44741f752750.png)


Nuget packages installed:
![image](https://user-images.githubusercontent.com/55366323/97927995-2feb3b80-1dba-11eb-9795-a9a34fc3ac50.png)


What am I missing?

Thanks,
Brent

**Comment by roubachof** [comment]
My bet would be a vs mac issue since like you said its still compiling and running fine

**Comment by brentpbc** [comment]
I think your right, it must be a bug with VS for Mac, it seems to have a problem with x:name, removing references to x:name removes the error for me:

```
<tabs:TabHostView
   Grid.Row="1"
   Margin="-16,0"
   BackgroundColor="{StaticResource SecondaryUltraLight}"
   SelectedIndex="{Binding SelectedViewModelIndex, Mode=TwoWay}">
  <tabs:TabHostView.Tabs>
       <tabs:UnderlinedTabItem Style="{StaticResource TabStyle}" Label="Details"/>
       <tabs:UnderlinedTabItem Style="{StaticResource TabStyle}" Label="ETS" />
       <tabs:UnderlinedTabItem Style="{StaticResource TabStyle}" Label="Items" />
    </tabs:TabHostView.Tabs>
</tabs:TabHostView>

<ScrollView Grid.Row="2" Padding="{StaticResource PaddingSmall}">
     <tabs:ViewSwitcher 
        Animate="True"
        SelectedIndex="{Binding SelectedViewModelIndex, Mode=TwoWay}">
            <controls:TestTabDetailView Animate="False" BindingContext="{Binding Details}" />
            <controls:TestTabView Animate="False" BindingContext="{Binding Ets}" />
            <controls:TestTabView Animate="False" BindingContext="{Binding Items}" />
    </tabs:ViewSwitcher>
</ScrollView>
```

**Comment by dylix** [comment]
i have this issue as well. on pc. initialized as follow in app.xaml.cs

            Sharpnado.Shades.Initializer.Initialize(false);
            Sharpnado.Tabs.Initializer.Initialize(true, true);

have tried different combinations, no luck

**Comment by roubachof** [comment]
Yup, you can fill a bug with the visual studio team.

**Comment by roubachof** [comment]
For all reading this issue.
If you see those errors **but** your project compiles and runs fine, this is a cosmetic VS issue.

**Comment by roubachof** [comment]
Also, there is specific versions of Xamarin.Forms that cause this issue (4.7):

https://github.com/xamarin/Xamarin.Forms/issues/11101

**Comment by jocontacter** [comment]
> For all reading this issue.
> If you see those errors **but** your project compiles and runs fine, this is a cosmetic VS issue.

Not certainly in that way. Because of this error, the Intellisence does not work for me. Also, not work hot reload, but I'm not sure what for this reason

**Comment by cmoore-cygnus** [comment]
Definitely not a mac issue. I have the same issue in VS on windows.

**Comment by skattegard** [comment]
I did have success with using the explicit xmlns for Tabs-controls. The compile error disappeared and Hot Reload started working again.

`xmlns:tab="clr-namespace:Sharpnado.Tabs;assembly=Sharpnado.Tabs"`
