### ISSUE TITLE
Binding Context of View is Changed

### ISSUE THREAD

**Issue by gktval** [roubachof/Sharpnado.Tabs#57]
**Platform**
 - OS: Both
 - Device: all
 - MAUI: [6.0.540]

**Describe the bug**
Inserting the view in the tab removes the view's BindingContext

**To Reproduce**
I have a content view with the binding context set in view, such as the code below where it is set in xaml:
```
<ContentView.BindingContext>
        <model:MyViewModel/>
</ContentView.BindingContext>
 ```

When I put this view in the DelayedView (or the LazyView) it changes the binding of the view to the parent's page BindingContext
Here is the code for the page:
```
<tabs:ViewSwitcher x:Name="Switcher" Grid.RowSpan="4" Margin="0" Animate="True"
                                           SelectedIndex="{Binding SelectedViewModelIndex, Mode=TwoWay}">

          <tabs:DelayedView Animate="True">
                   <views:MyViewWithItsOwnBindingContext/>
          </tabs:DelayedView>

           <tabs:DelayedView x:TypeArguments="views:MySecondView" Animate="True" />
</tabs:ViewSwitcher>
```

**Comment by janusw** [comment]
I think I may be seeing the same problem: LazyView messing up my bindings (using Maui 8.0.40 on Android and iOS).

What causes it is probably this:

https://github.com/roubachof/Sharpnado.Tabs/blob/e8dc4e2446e510797a334a1c66f3b397361027fc/Tabs/Tabs/LazyView.cs#L116

@roubachof What's the reason for resetting the `BindingContext` here? Do you have any comments on this issue?

**Comment by roubachof** [comment]
It's the default behavior, if you don't want the binding context to propagate just inherit from LazyView and override LoadView
