### ISSUE TITLE
[MAUI] Package Sharpnado.Tabs.Maui 3.0.0 is not compatible with net6.0

### ISSUE THREAD

**Issue by tranb3r** [roubachof/Sharpnado.Tabs#59]
I'm currently migrating my Xamarin.Forms app to Maui.

The architecture of my app looks like this: ios/android app -> UI library -> Core library

ios/android app projects hold the platform specific code required to start the app
UI library holds the UI code (pages, view)
Core libreary holds the business logic code (view models, services, models...)
In the Xamarin app, both UI and Core libraries are netstandard projects.
The UI library references the Sharpnado.Tabs package (since it suports the netstandard TFM).

In my Maui app, both UI and Core libraries are net6.0 projects.
However I find it impossible to reference the Sharpnado.Tabs.Maui package in the UI library.
It expects a net6.0-android / net6.0-ios TFM.
But there is no reason for that, since this is a cross-platform library, with no specific code to compile.

```
Error	NU1202	
Package Sharpnado.Tabs.Maui 3.0.0 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). 
Package Sharpnado.Tabs.Maui 3.0.0 supports:
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios15.4 (.NETCoreApp,Version=v6.0)
```
Could you please make sure this package can be installed in a net6.0 project?

Thanks

**Comment by roubachof** [comment]
Mmmh I see. I had to add a platform agnostic target.

**Comment by Masgharoth** [comment]
any workarounds or updates?

**Comment by roubachof** [comment]
version 3.0.1 includes a .net6 targhet
