### ISSUE TITLE
[MAUI] warning MSB3270: There was a mismatch between the processor architecture of the project being built...

### ISSUE THREAD

**Issue by tranb3r** [roubachof/Sharpnado.Tabs#63]
**Platform**
 - OS: iOS
 - MAUI: latest

**Describe the bug**
When adding the Sharpnado.Tabs.Maui nuget to a simple class library targeting net6.0-ios, I get the following warning when building the library:
```
warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Nuget\sharpnado.tabs.maui\3.0.0\lib\net6.0-ios15.4\Maui.Tabs.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
```
Could you please help me understand it and fix it ?

**To Reproduce**
1. Create a class library for net6.0 
2. Target net6.0-ios (see csproj below)
3. Add a package reference to Sharpnado.Tabs.Maui (3.0.0)
4. Build library
5. See warning

csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0-android;net6.0-ios</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Sharpnado.Tabs.Maui" Version="3.0.0" />
  </ItemGroup>
</Project>
```

**Comment by angelru** [comment]
Same issue

**Comment by angelru** [comment]
> @angelru Logré deshacerme de la advertencia agregando la siguiente propiedad al csproj:
> 
> ```
> 	<PropertyGroup Condition="'$(BuildingInsideVisualStudio)' == 'True'">
> 		<PlatformTarget>x64</PlatformTarget>
> 	</PropertyGroup>
> ```
> 
> Sin embargo, es solo una solución alternativa, sería mejor solucionar la causa raíz en esta biblioteca si es posible.

but it works fine on iOS?

**Comment by tranb3r** [comment]
> but it works fine on iOS?
I've only tested on simulator so far...

**Comment by roubachof** [comment]
I have to figure out how the compatibility with the framework versions works...
If someone could enlighten me:

I thought a .net6 lib could be use in a .net7 project, but it seems the other way around according to:
[.NET 7 breaking change: Library support for older frameworks - .NET](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/old-framework-support)

> .NET 7 core libraries packages are supported for use in projects targeting .NET Framework 4.6.2 and later, .NET 6 and later, or .NET Standard 2.0 or later.

So could someone confirm I just have to always upgrade my libs to the latest .net version to be compatible with the larger number of projects ?

**Comment by roubachof** [comment]
yup, maui ios workload issue. filed here: https://github.com/xamarin/xamarin-macios/issues/17075

**Comment by roubachof** [comment]
in fact .net 6 libs can be used in .net 7 projects, so it's really a build issue,

**Comment by roubachof** [comment]
were an issue in the `csproj.user` file (wtf).
Version 3.0.1 fixes the issue
