### ISSUE TITLE
[MAUI] .Net7 Support

### ISSUE THREAD

**Issue by JosueSquareSix** [roubachof/Sharpnado.Tabs#64]
Thanks in advance for this AMAZING library!

**Platform (please complete the following information):**
 - OS: Android
 - Device: Android devices and emulators
 - SDK version: Android SDK 31
 - MAUI: 7.0.100

**Describe the bug**
Deploying an app that was built in release mode targeting Android will fail after the app launch.

**To Reproduce**
1. Install Sharpnado.Tabs.Maui in a Blank project using .Net7
2. Build and Deploy in Release mode to Android Device.
3. See the error

**Exceptions (if applicable)**

```
Error Message from VS: The selected execution mode is not supported for .Net projects
```

**Comment by roubachof** [comment]
this a vs issue:
https://github.com/dotnet/maui/issues/8894

**Comment by roubachof** [comment]
probably related to #63

**Comment by roubachof** [comment]
yup, this has nothing to do with .net 7, I filed an issue here: https://github.com/xamarin/xamarin-macios/issues/17075

net6 libs can normally be used in .net 7 project.
I'm closing that one since it's a duplicate
