### ISSUE TITLE
Problem with SegmentedTabItem

### ISSUE THREAD

**Issue by ssotir** [roubachof/Sharpnado.Tabs#7]
**Platform (please complete the following information):**
 - OS: Android
 - Device: AndroidEmulator
 - Sdk vervion: Android SDK 29
 - Xamarin.Forms: 4.7.0.1351

**Describe the bug**
Downloaded the sample, uncommented the element underneath  in the SillyDudePage.xaml and commented the previous one. 

The Tabs seems to draw 4 tabs instead of 3. The last one seems to be a dummy one.

**Screenshots (if applicable)**
![Screenshot_1604185994](https://user-images.githubusercontent.com/3126292/97791894-30c87580-1be0-11eb-84ac-e540969b2ec6.png)

**Comment by roubachof** [comment]
Set TabType to fixed instead of scrollable

**Comment by ssotir** [comment]
But it is TabType="Fixed"
It seems to me that the whole problem is in the OnChildAdded of TabHostView when SegmentedHasSeparator="True"

**Comment by roubachof** [comment]
Please show me the xaml

**Comment by ssotir** [comment]
It is in your example 

`        <tabs:TabHostView x:Name="TabHost"
                          Grid.Row="4"
                          HeightRequest="40"
                          Margin="20,15,20,0"
                          VerticalOptions="Center"
                          BackgroundColor="{DynamicResource DynamicDudeBackgroundColor}"
                          CornerRadius="20"
                          IsSegmented="True"
                          SegmentedHasSeparator="True"
                          SegmentedOutlineColor="{DynamicResource DynamicOutlineColor}"
                          Shades="{DynamicResource DynamicTabsShadow}"
                          TabType="Fixed"
                          SelectedIndex="{Binding Source={x:Reference Switcher}, Path=SelectedIndex, Mode=TwoWay}">
          <tabs:TabHostView.Tabs>
            <tabs:SegmentedTabItem Style="{StaticResource SegmentedTabStyle}"
                                   Label="Quote" />
            <tabs:SegmentedTabItem Style="{StaticResource SegmentedTabStyle}"
                                   Label="Movies" />
            <tabs:SegmentedTabItem Style="{StaticResource SegmentedTabStyle}"
                                   Label="Meme" />
          </tabs:TabHostView.Tabs>
        </tabs:TabHostView>`

and I use Tabs 2

**Comment by roubachof** [comment]
Ok must be some kind of regression... will have a look 😀

**Comment by ssotir** [comment]
As I've said earlier, I strongly believe it is the logic you use to add the separator and the grid columns you create.

**Comment by roubachof** [comment]
I'm an atheist. So I only believe in facts xo)

**Comment by ssotir** [comment]
No matter what, you ... believe in something as you say. Waiting for your research results. You have done a lovely work here.

**Comment by mgierlasinski** [comment]
Looks lite problem with segmented tabs only:

![image](https://user-images.githubusercontent.com/19707868/97896263-22d83900-1d35-11eb-88ee-5a4b4f4e628d.png)

**Comment by roubachof** [comment]
Will fix that tomorrow :)

**Comment by roubachof** [comment]
fixed by https://github.com/roubachof/Sharpnado.Tabs/releases/tag/v2.0.1
