### ISSUE TITLE
[MAUI/Xamarin.Forms/Both] supported  .NET7？

### ISSUE THREAD

**Issue by simphonydeveloper** [roubachof/Sharpnado.Tabs#75]
I cannot use it after installing with nuget.

**Comment by roubachof** [comment]
The maui nuget target .net6 which can be used in .net7

**Comment by simphonydeveloper** [comment]
Change the TargetFrameworks of the project.

**Comment by simphonydeveloper** [comment]
I have a test today and found that it cannot be used on. NET 7.

**Comment by roubachof** [comment]
which platform ?

**Comment by simphonydeveloper** [comment]
Andriod

**Comment by roubachof** [comment]
just tested it on net7.0-android, it works as expected
![image](https://user-images.githubusercontent.com/596903/222090230-9f01b3ec-8c35-462f-8c6e-c53117a9913f.png)

**Comment by simphonydeveloper** [comment]
What do you set after installing the nuget package?
I can run your example.
There is another problem. I run the sample and then slide the contents of the tab with my finger. It will not jump.

**Comment by roubachof** [comment]
sorry this is 2 differents issues, and the second one is a duplicate of an existing enhancement

**Comment by simphonydeveloper** [comment]
Thank you for your reply and look forward to your new features.
