### ISSUE TITLE
[MAUI] Underline on Android not changing in ScrollableTabs

### ISSUE THREAD

**Issue by bmclane** [roubachof/Sharpnado.Tabs#78]
**Platform (please complete the following information):**
 - OS: [Android]
 - Device: [Pixel/AndroidEmulator/]
 - MAUI: [7.0.59]

**Describe the bug**
Underline is not changing when using scrollable tabs on Android

**To Reproduce**
1. Open the MauiSample Application on Android
2. Change the Scrollable Tabs, the underline doesn't change. (Note: only happens on scrollable)

**Screenshots (if applicable)**
On Android Super is still underlined when Maui is selected, and Maui is not underlined:
![image](https://user-images.githubusercontent.com/5350765/225358327-9785c93b-4473-439c-b8b0-fecc37450467.png)

On iOS it is correct:
![image](https://user-images.githubusercontent.com/5350765/225359083-04e77408-ff71-4480-b507-fe9989e07d16.png)

**Comment by roubachof** [comment]
was a maui 7 bug
