### ISSUE TITLE
Tab Icon Dynamic Resource Colors Not Changing after tapping on them

### ISSUE THREAD

**Issue by mauro-dasilva** [roubachof/Sharpnado.Tabs#8]
**Platform (please complete the following information):**
 - OS: [Both]
 - Device: [Pixel/AndroidEmulator/iPhone 7]
 - Sdk vervion: [iOS 14.1/Android SDK 28]
 - Xamarin.Forms: [4.6.0]

**Describe the bug**
I have a Dynamic Resource color which is being swapped out if the user changes from Light to Dark mode and vice versa. If the user doesn't tap any of the tab icons, the colors change fine. However, after they have tapped on the tab icon, and you try to change the color, the color is not updated anymore.

**To Reproduce**
1. Load up the attached sample
2. On the screen that loads, click the 'Change Color' button. You will see that all the home icons change color, which is correct
3. Tap on one or two of the home icons and then click the 'Change Color' button again. 
4. You will see that only the icons that you haven't clicked on before will be updated. If you tap on all the home icons, then no colors will ever be updated

**Exceptions (if applicable)**
N/A

**Screenshots (if applicable)**
See attached sample

[App2.zip](https://github.com/roubachof/Sharpnado.Tabs/files/5482065/App2.zip)

**Comment by roubachof** [comment]
mmmh probably linked to #20

**Comment by roubachof** [comment]
will be fixed in 2.1

**Comment by leonedev** [comment]
This bug still persist, the issue remains!
