### ISSUE TITLE
[MAUI] DelayedView with Content does not delay

### ISSUE THREAD

**Issue by daltzctr** [roubachof/Sharpnado.Tabs#85]
**Platform (please complete the following information):**
 - OS: Android 14
 - Device: Pixel 6a (real)
 - Minimum SDK: Android 9, Target SDK, Android 13
 - MAUI: 8.0 preview 4

**Describe the bug**
DelayedView using inner content instead of Type arguments does not delay view rendering.

**To Reproduce**
Plop the following XAML somewhere

```
<tabs:DelayedView DelayInMilliseconds="200000">
   <Label Text="Hi, I should be delayed"/>
</tabs:DelayedView>
```

**Comment by daltzctr** [comment]
Hm, `DelayedView` actually does not handle `Content` being set, and specifically requires `View` arguments. I'd like to refactor this bug report into a feature request. 

The use case is using DelayedView for things outside of tabs, just for general lazy intialization of heavy GUI items.

**Comment by roubachof** [comment]
Do refactor

**Comment by roubachof** [comment]
Sorry! thought you created a feature request for this one.
Anyway I don't really understand the issue here, just use the `View` property instead of the content.

```xml
<DelayedView>
	<DelayedView.View>
		<YourContent />
	</DelayedView.View>
</DelayedView>
```
