### ISSUE TITLE
[MAUI/Xamarin.Forms/Both]

### ISSUE THREAD

**Issue by South2AK** [roubachof/Sharpnado.Tabs#92]
**Platform (please complete the following information):**
 - OS: Android 13
 - Device: Samsung Galaxy S22 Ultra
 - Sdk vervion: Android API 33

I´m trying to add DelayedView on a Page but all I´m getting is the activitiyindicator spinning. The content never shows.

**To Reproduce**
```
<ContentPage.Content>
    
        <tabs:DelayedView  UseActivityIndicator="True">
            <tabs:DelayedView.View>
                 <StackLayout>
                        <Label Text="Test" TextColor="black"/>
                  </StackLayout>
            
            </tabs:DelayedView.View>
            
        </tabs:DelayedView>
</ContentPage.Content>
```

**Comment by roubachof** [comment]
You have to load the delayed view at some point. Please read the docs.
