### ISSUE TITLE
UnderlinedTabItem IconImageSource

### ISSUE THREAD

**Issue by loncho67880** [roubachof/Sharpnado.Tabs#98]
Hi,

I want to know if you will add IconImageSource in the UnderlinedTabItem, i need that in this moment :(

**Comment by roubachof** [comment]
It's supported, read the docs :)

**Comment by loncho67880** [comment]
I can't see any property to add one icon in the UnderlinedTabItem:

![image](https://github.com/roubachof/Sharpnado.Tabs/assets/21958802/764fe574-d573-4982-bef7-5403efbfc77c)

**Comment by roubachof** [comment]
Scroll the docs...

**Comment by loncho67880** [comment]
I saw that i can using MaterialUnderlinedTabItem, you refer to this? if is using MaterialUnderlinedTabItem is necesary to add other aditional nuget?

**Comment by roubachof** [comment]
BINGO! you won
